apiVersion: v1
kind: ConfigMap
metadata:
  name: ig-metrics-config
  namespace: default
  labels:
    name: ig-metrics-config
data:
  metrics-config.yaml: |-
    metrics_name: kubeconna2023
    metrics:
      - name: executed_processes
        type: counter
        category: trace
        gadget: exec
        labels:
          - k8s.namespace
          - k8s.pod
          - k8s.container
          - comm

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ig
  labels:
    app: ig
spec:
  selector:
    matchLabels:
      app: ig
  template:
    metadata:
      labels:
        app: ig
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2223"
        prometheus.io/path: "/metrics"
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: exporter
        #image: ghcr.io/mauriciovasquezbernal/ig:kubeconna2023
        #image: ghcr.io/inspektor-gadget/ig:latest
        # Above images fail with "error: filesystems tracefs not mounted (did you try --auto-mount-filesystems?)"
        image: ghcr.io/inspektor-gadget/ig:v0.21.0
        command: ["ig"]
        args: ["--auto-mount-filesystems", "prometheus", "--config", "@/var/ig/metrics-config.yaml"]
        env:
        - name: IG_EXPERIMENTAL
          value: "true"
        - name: HOST_ROOT
          value: "/host"
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /host
            name: host
          - mountPath: /run
            name: run
          - mountPath: /lib/modules
            name: modules
          - mountPath: /sys/kernel/debug
            name: debugfs
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - mountPath: /sys/fs/bpf
            name: bpffs
          - name: config
            mountPath: /var/ig/
      volumes:
        - name: host
          hostPath:
            path: /
        - name: run
          hostPath:
            path: /run
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: modules
          hostPath:
            path: /lib/modules
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: config
          configMap:
            name: ig-metrics-config
